import { v4 as uuidv4 } from "uuid";

export const mockCandidates = {
  company_name: "Peerlist",
  company_logo:
    "https://dqy38fnwh4fqs.cloudfront.net/website/peerlist-logo-full.svg",
  role: "Frontend Engineer,Frontend",
  location: " Remote (United States, Canada)",
  job_type: "Full time",
  views: 50,
  total_candidates: 20,
  applied_with_peerlist: 9,
  applied_externally: 11,
  posted_by: "Akash Bhadange",
  days_before: "1day",
  applicants: [
    {
      id: `item-${uuidv4()}`,
      name: "Esther Howard",
      profile_image: "assets/images/users/u1.svg",
      current_role: "Cloud Consultant",
      verified: true,
      referred_by: {
        name: "Adam",
        profile_picture: "assets/images/user2.png",
      },
      current_company: "Rapid Circle",
      applied: "1d",
      years_of_experience: "11y 6m",
      holding_offer: true,
      notice_period: "Immediate",
      contact: {
        email: "darrell.stewards@emaildomain.com",
        phone: "+1 12345 67490",
      },
      status: "shortlisted",
      shortlisted: {
        status: true,
        by: "Yogini Bende",
        at: "15 Dec 2023",
      },
      resume: "DarrellSteward.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "John Doe",
      profile_image: "assets/images/users/u2.svg",
      current_role: "Software Engineer",
      verified: true,
      referred_by: {
        name: "Adam",
        profile_picture: "assets/images/user2.png",
      },
      current_company: "Tech Solutions Inc.",
      applied: "2d",
      years_of_experience: "8y",
      holding_offer: false,
      notice_period: "30 days",
      contact: {
        email: "john.doe@emaildomain.com",
        phone: "+1 98765 43210",
      },
      status: "applied",
      resume: "JohnDoe.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "Alice Johnson",
      profile_image: "assets/images/users/u3.svg",
      current_role: "Frontend Developer",
      verified: false,
      referred_by: null,
      current_company: "WebTech Solutions",
      applied: "3d",
      years_of_experience: "6y",
      holding_offer: true,
      notice_period: "15 days",
      contact: {
        email: "alice.johnson@emaildomain.com",
        phone: "+1 23456 78901",
      },
      status: "rejected",
      shortlisted: {
        status: false,
        by: "Yogini Bende",
        at: "15 Dec 2023",
      },
      resume: "AliceJohnson.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "Michael Smith",
      profile_image: "assets/images/users/u4.svg",
      current_role: "UI/UX Designer",
      verified: true,
      referred_by: null,
      current_company: "DesignWorks",
      applied: "4d",
      years_of_experience: "7y",
      holding_offer: false,
      notice_period: "Immediate",
      contact: {
        email: "michael.smith@emaildomain.com",
        phone: "+1 34567 89012",
      },
      status: "shortlisted",
      shortlisted: {
        status: true,
        by: "Yogini Bende",
        at: "15 Dec 2023",
      },
      resume: "MichaelSmith.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "Emily Wang",
      profile_image: "assets/images/users/u5.svg",
      current_role: "Product Manager",
      verified: true,
      referred_by: null,
      current_company: "ProdWorks",
      applied: "5d",
      source: "external",
      notice_period: "30 days",
      status: "applied",
      contact: {
        email: "",
        phone: "",
      },
      resume: "EmilyWang.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "David Brown",
      profile_image: "assets/images/users/u6.svg",
      current_role: "Full Stack Developer",
      verified: true,
      referred_by: null,
      current_company: "CodeMasters",
      applied: "6d",
      years_of_experience: "5y",
      holding_offer: true,
      notice_period: "Immediate",
      contact: {
        email: "david.brown@emaildomain.com",
        phone: "+1 56789 01234",
      },
      status: "rejected",

      shortlisted: {
        status: false,
        by: "Yogini Bende",
        at: "15 Dec 2023",
      },
      resume: "DavidBrown.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "Sophia Garcia",
      profile_image: "assets/images/users/u1.svg",
      current_role: "Software Developer",
      verified: true,
      referred_by: {
        name: "Adam",
        profile_picture: "assets/images/user2.png",
      },
      current_company: "TechHub",
      applied: "7d",
      years_of_experience: "3y",
      holding_offer: false,
      notice_period: "10 days",
      contact: {
        email: "sophia.garcia@emaildomain.com",
        phone: "+1 67890 12345",
      },
      status: "shortlisted",
      shortlisted: {
        status: true,
        by: "Yogini Bende",
        at: "15 Dec 2023",
      },
      resume: "SophiaGarcia.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "Daniel Martinez",
      profile_image: "assets/images/users/u8.svg",
      current_role: "Frontend Developer",
      verified: true,
      referred_by: null,
      current_company: "WebTech Solutions",
      applied: "8d",
      years_of_experience: "4y",
      holding_offer: false,
      notice_period: "Immediate",
      contact: {
        email: "daniel.martinez@emaildomain.com",
        phone: "+1 78901 23456",
      },
      status: "applied",
      resume: "DanielMartinez.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "Mia Johnson",
      profile_image: "assets/images/users/u9.svg",
      current_role: "UI/UX Designer",
      verified: true,
      referred_by: null,
      current_company: "DesignWorks",
      applied: "9d",
      years_of_experience: "6y",
      holding_offer: false,
      notice_period: "20 days",
      contact: {
        email: "mia.johnson@emaildomain.com",
        phone: "+1 89012 34567",
      },
      status: "rejected",
      shortlisted: {
        status: false,
        by: "Yogini Bende",
        at: "15 Dec 2023",
      },
      resume: "MiaJohnson.pdf",
      matched: false,
    },
    {
      id: `item-${uuidv4()}`,
      name: "William Taylor",
      profile_image: "assets/images/users/u10.svg",
      current_role: "Software Engineer",
      verified: true,
      referred_by: null,
      current_company: "Tech Solutions Inc.",
      applied: "10d",
      years_of_experience: "7y",
      holding_offer: false,
      notice_period: "15 days",
      contact: {
        email: "william.taylor@emaildomain.com",
        phone: "+1 90123 45678",
      },
      status: "shortlisted",
      shortlisted: {
        status: true,
        by: "Yogini Bende",
        at: "15 Dec 2023",
      },
      resume: "WilliamTaylor.pdf",
      matched: false,
    },
  ],
};
